management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    metrics:
      export:
        prometheus:
          enabled: true

mongodbDatabase: exampleDb
mongodbUri: mongodb://${MONGO_DB_USER:admin}:${MONGO_DB_PASS:admin123}@127.0.0.1:27017
apiPort: 9898
grpcPort: 9090

smpp:
  host: smpp.server.host
  port: 2775
  system-id: yourSystemId
  password: yourPassword